Object method files and linters configuration
sserwangaedrisa/Awesome-Books-Store pull request #2
Opened 2023-09-13 20:35 UTC by sserwangaedrisa

Object method files and linters configuration.

2023-09-13 21:45 UTC, arnoldnekemiah requested changes
Hello @sserwangaedrisa ,
I see you have tried to do the work as best as you understood the assignment. But there are Changes required to make your project functional;

- Make sure you follow the guide lines of the project.

2023-09-13 21:45 UTC, arnoldnekemiah commented on index.js
> +    newAuthor.textContent = JSON.parse(localStorage.getItem(key)).Author;
I see you have tried a path to using `LocalStorage`, but the approach is not viable and You are not accessing Local Storage
![image](https://github.com/sserwangaedrisa/Awesome-Books-Store/assets/42886828/5f489329-0c25-4230-8f9a-1bc78a6ccfe1)
From the Image above you can see that data is not being loaded into local Storage.
Internalize the approach below and work on the remaining;

 _check if the local storage is empty, then add empty array_
```
if (localStorage.getItem('Added books') == null) {
  localStorage.setItem('Added books', JSON.stringify([]));
}
```
That is an example on how to handle localStorage, that way you can make functions referencing it by key

2023-09-13 21:45 UTC, arnoldnekemiah commented on .gitignore
> +.vscode/
What is this. Is it necessary?

2023-09-13 21:45 UTC, arnoldnekemiah commented on index.js
> +
Create a function for removing button as suggested i the guidelines

2023-09-13 21:45 UTC, arnoldnekemiah commented on index.js
> +  author.value = '';
You can also write a function to clear inputs after submission.

2023-09-13 21:45 UTC, arnoldnekemiah commented on index.js
> +    };
This should also be a function, such that you can invoke it whenever you need it.

2023-09-13 22:06 UTC, sserwangaedrisa commented
I'm going to work on it tomorrow..

On Thu, Sep 14, 2023, 12:45 AM IKONDE NEKEMIAH ARNOLD <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hello @sserwangaedrisa <https://github.com/sserwangaedrisa> ,
> I see you have tried to do the work as best as you understood the
> assignment. But there are Changes required to make your project functional;
>
>    - Make sure you follow the guide lines of the project.
>
> ------------------------------
>
> In index.js
> <https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2#discussion_r1325093663>
> :
>
> > +const keys = Object.keys(localStorage);
> +if (localStorage.length > 0) {
> +  keys.forEach((key) => {
> +    const newTitle = document.createElement('p');
> +    newTitle.textContent = JSON.parse(localStorage.getItem(key)).Title;
> +    const newAuthor = document.createElement('p');
> +    newAuthor.textContent = JSON.parse(localStorage.getItem(key)).Author;
>
> I see you have tried a path to using LocalStorage, but the approach is
> not viable and You are not accessing Local Storage
> [image: image]
> <https://user-images.githubusercontent.com/42886828/267792541-5f489329-0c25-4230-8f9a-1bc78a6ccfe1.png>
> From the Image above you can see that data is not being loaded into local
> Storage.
> Internalize the approach below and work on the remaining;
>
> *check if the local storage is empty, then add empty array*
>
> if (localStorage.getItem('Added books') == null) {
>   localStorage.setItem('Added books', JSON.stringify([]));
> }
>
> That is an example on how to handle localStorage, that way you can make
> functions referencing it by key
> ------------------------------
>
> In .gitignore
> <https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2#discussion_r1325101869>
> :
>
> > @@ -0,0 +1,2 @@
> +node_modules/
> +.vscode/
>
> What is this. Is it necessary?
> ------------------------------
>
> In index.js
> <https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2#discussion_r1325106374>
> :
>
> > +    removeBtn.addEventListener('click', () => {
> +      localStorage.removeItem(removeBtn.id);
> +      window.location.reload();
> +    });
> +
>
> Create a function for removing button as suggested i the guidelines
> ------------------------------
>
> In index.js
> <https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2#discussion_r1325107661>
> :
>
> > +  title.value = '';
> +  author.value = '';
>
> You can also write a function to clear inputs after submission.
> ------------------------------
>
> In index.js
> <https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2#discussion_r1325109578>
> :
>
> > +addButton.addEventListener('click', () => {
> +  if (title.value.length !== 0) {
> +    const inputs = {
> +      Title: title.value,
> +      Author: author.value,
> +    };
>
> This should also be a function, such that you can invoke it whenever you
> need it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2#pullrequestreview-1625476135>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A57GCMKLAPRPUJI5E24NS5TX2ISRLANCNFSM6AAAAAA4XCAAPQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-14 10:04 UTC, sserwangaedrisa commented
Hey there, this is how i tried to modify the project

https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2


On Thu, Sep 14, 2023 at 1:06 AM Sserwanga Edrisa ***@***.***>
wrote:

> I'm going to work on it tomorrow..
>
> On Thu, Sep 14, 2023, 12:45 AM IKONDE NEKEMIAH ARNOLD <
> ***@***.***> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Hello @sserwangaedrisa <https://github.com/sserwangaedrisa> ,
>> I see you have tried to do the work as best as you understood the
>> assignment. But there are Changes required to make your project functional;
>>
>>    - Make sure you follow the guide lines of the project.
>>
>> ------------------------------
>>
>> In index.js
>> <https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2#discussion_r1325093663>
>> :
>>
>> > +const keys = Object.keys(localStorage);
>> +if (localStorage.length > 0) {
>> +  keys.forEach((key) => {
>> +    const newTitle = document.createElement('p');
>> +    newTitle.textContent = JSON.parse(localStorage.getItem(key)).Title;
>> +    const newAuthor = document.createElement('p');
>> +    newAuthor.textContent = JSON.parse(localStorage.getItem(key)).Author;
>>
>> I see you have tried a path to using LocalStorage, but the approach is
>> not viable and You are not accessing Local Storage
>> [image: image]
>> <https://user-images.githubusercontent.com/42886828/267792541-5f489329-0c25-4230-8f9a-1bc78a6ccfe1.png>
>> From the Image above you can see that data is not being loaded into local
>> Storage.
>> Internalize the approach below and work on the remaining;
>>
>> *check if the local storage is empty, then add empty array*
>>
>> if (localStorage.getItem('Added books') == null) {
>>   localStorage.setItem('Added books', JSON.stringify([]));
>> }
>>
>> That is an example on how to handle localStorage, that way you can make
>> functions referencing it by key
>> ------------------------------
>>
>> In .gitignore
>> <https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2#discussion_r1325101869>
>> :
>>
>> > @@ -0,0 +1,2 @@
>> +node_modules/
>> +.vscode/
>>
>> What is this. Is it necessary?
>> ------------------------------
>>
>> In index.js
>> <https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2#discussion_r1325106374>
>> :
>>
>> > +    removeBtn.addEventListener('click', () => {
>> +      localStorage.removeItem(removeBtn.id);
>> +      window.location.reload();
>> +    });
>> +
>>
>> Create a function for removing button as suggested i the guidelines
>> ------------------------------
>>
>> In index.js
>> <https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2#discussion_r1325107661>
>> :
>>
>> > +  title.value = '';
>> +  author.value = '';
>>
>> You can also write a function to clear inputs after submission.
>> ------------------------------
>>
>> In index.js
>> <https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2#discussion_r1325109578>
>> :
>>
>> > +addButton.addEventListener('click', () => {
>> +  if (title.value.length !== 0) {
>> +    const inputs = {
>> +      Title: title.value,
>> +      Author: author.value,
>> +    };
>>
>> This should also be a function, such that you can invoke it whenever you
>> need it.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/sserwangaedrisa/Awesome-Books-Store/pull/2#pullrequestreview-1625476135>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A57GCMKLAPRPUJI5E24NS5TX2ISRLANCNFSM6AAAAAA4XCAAPQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2023-09-15 18:45 UTC, arnoldnekemiah approved these changes
Congs @sserwangaedrisa , 
Your Project is complete, There is nothing more to say other than, it's time to merge it.
![well-done](https://github.com/sserwangaedrisa/Awesome-Books-Store/assets/42886828/d4902bf6-2520-432f-a65c-f0dbf1ac88bf)

I will inform you of the next level of the project. For now Merge the branch

2023-09-15 18:48 UTC, arnoldnekemiah commented
Make sure Your linters are running I see no history of linter checks in the Pull request

2023-09-15 18:50 UTC, arnoldnekemiah requested changes
Please make sure linters are well configured. Your project is missing `linters.yml` file in the _.github/workflow_s folder.
That is why there are no checks

2023-10-14 13:57 UTC, merged